### ISSUE TITLE
Compiler error when setting compiler warning level to 'more'

### ISSUE THREAD

**Issue by Jingjok86** [gmag11/NtpClient#59]
Great library !

I am using the newest master branch with ESP32. One small issue I found is that the compiler errors (it treats the warning as an error), when the compiler warning level in the Arduino IDE preferences is set to 'more' instead of 'default'. 

D:\Documents\My Documents\Arduino\libraries\NtpClientLib\src\NTPClientLib.cpp: In member function 'bool NTPClient::summertime(int, byte, byte, byte, byte)':

D:\Documents\My Documents\Arduino\libraries\NtpClientLib\src\NTPClientLib.cpp:356:20: error: suggest parentheses around '&&' within '||' [-Werror=parentheses]

     if (month == 3 && (hour + 24 * day) >= (1 + tzHours + 24 * (31 - (5 * year / 4 + 4) % 7)) || month == 10 && (hour + 24 * day) < (1 + tzHours + 24 * (31 - (5 * year / 4 + 1) % 7)))

                    ^

cc1plus.exe: some warnings being treated as errors

**Comment by gmag11** [comment]
Latest commit https://github.com/gmag11/NtpClient/commit/28af3a5f8d3ad01870fd8bd8ee12319d2fa5d842 should ammend this, please try

**Comment by Jingjok86** [comment]
Hi,

it is still not working, looks like you have removed the fix again with your addition of the DST_ZONE_EU ?
The additional brackets for the line that errors were there before this change :

```
-    if ((month < 3) || (month > 10)) return false; // keine Sommerzeit in Jan, Feb, Nov, Dez 
-    if ((month > 3) && (month < 10)) return true; // Sommerzeit in Apr, Mai, Jun, Jul, Aug, Sep 
-    if ((month == 3 && (hour + 24 * day) >= (1 + tzHours + 24 * (31 - (5 * year / 4 + 4) % 7))) || (month == 10 && (hour + 24 * day) < (1 + tzHours + 24 * (31 - (5 * year / 4 + 1) % 7)))) 
-        return true; 
-    else 
-        return false; 
 
+    if (DST_ZONE_EU == _dstZone) { 
+        if ((month < 3) || (month > 10)) return false; // keine Sommerzeit in Jan, Feb, Nov, Dez 
+        if ((month > 3) && (month < 10)) return true; // Sommerzeit in Apr, Mai, Jun, Jul, Aug, Sep 
+        if (month == 3 && (hour + 24 * day) >= (1 + tzHours + 24 * (31 - (5 * year / 4 + 4) % 7)) || month == 10 && (hour + 24 * day) < (1 + tzHours + 24 * (31 - (5 * year / 4 + 1) % 7))) 
+            return true; 
+        else 
+            return false; 
+}
```

**Comment by Jingjok86** [comment]
There is actually now a second compiler error, because the compiler does not like that there is no return statement in the main block :

D:\Documents\My Documents\Arduino\libraries\NtpClient-develop\src\NTPClientLib.cpp:418:1: error: control reaches end of non-void function [-Werror=return-type]

**Comment by gmag11** [comment]
It should be solved now

**Comment by morgapa** [comment]
Hello, and I'm in Europe, and I have this error
Arduino: 1.8.5 (Windows 10), Board: "Generic ESP8266 Module, 80 MHz, ck, 26 MHz, 40MHz, QIO, 512K (no SPIFFS), 2, v2 Lower Memory, Disabled, None, Only Sketch, 115200"

C:\arduino-1.8.5\espurna-dev\code\espurna\ntp.ino: In function 'void _ntpStart()':

ntp:40: error: 'class NTPClient' has no member named 'setNTPTimeout'

     NTP.setNTPTimeout(NTP_TIMEOUT);

         ^

C:\arduino-1.8.5\espurna-dev\code\espurna\ntp.ino: In function 'void _ntpConfigure()':

ntp:71: error: 'class NTPClient' has no member named 'setDSTZone'

     NTP.setDSTZone(dst_region);

         ^

exit status 1
'class NTPClient' has no member named 'setNTPTimeout'

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by morgapa** [comment]
i still have the same problem, and same time they change  alone the perferences/network/ to auto-detect proxy setings 
![screenshot 2018-03-17 19 43 37](https://user-images.githubusercontent.com/34972574/37559320-a59f564e-2a1b-11e8-9621-e188dead25ee.jpg)

**Comment by gmag11** [comment]
Library has just updated together with Espurna developer. I guess you do not have the latest library version. Get it from https://github.com/gmag11/NtpClient/tree/develop
As soon as testing is finished it will be assigned with a new library version number and merged into master branch

**Comment by morgapa** [comment]
Muchas gracias Germán, now is working

**Comment by Jingjok86** [comment]
Hi,

The same 2 errors are still there in the newest code from the develop branch (downloaded just now) when changing preferences compiler warnings to 'more' in Arduino IDE.

I really don't want to be rude as your work is very much appreciated, but could you please test it next time instead of just claiming 'it should be fixed now' ?



D:\Documents\My Documents\Arduino\libraries\NtpClient-develop\src\NTPClientLib.cpp: In member function 'bool NTPClient::summertime(int, byte, byte, byte, byte, byte)':

D:\Documents\My Documents\Arduino\libraries\NtpClient-develop\src\NTPClientLib.cpp:386:24: **error: suggest parentheses around '&&' within '||' [-Werror=parentheses]**

         if (month == 3 && ((hour + 24 * day) >= (1 + tzHours + 24 * (31 - (5 * year / 4 + 4) % 7))) || (month == 10 && (hour + 24 * day) < (1 + tzHours + 24 * (31 - (5 * year / 4 + 1) % 7))))

                        ^

D:\Documents\My Documents\Arduino\libraries\NtpClient-develop\src\NTPClientLib.cpp:418:1: **error: control reaches end of non-void function [-Werror=return-type]**

 }

 ^

cc1plus.exe: some warnings being treated as errors

**Comment by gmag11** [comment]
It should be solved with latest commits. Thanx
